
services:
  reminder:
    build: .
    ports:
      - "9080:9080"
    depends_on:
      - postgresql
    environment:
      POSTGRESQL_DSN: ${POSTGRESQL_DSN}
    volumes:
      - ./migrations:/app/migrations

  migrator:
    build: .
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      POSTGRESQL_DSN: ${POSTGRESQL_DSN}
    entrypoint: [ "goose", "-dir", "/app/migrations", "postgres", "${POSTGRESQL_DSN}", "up" ]


  postgresql:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: