#common:
#  path_prefix: /var/loki
#
#compactor:
#  working_directory: /var/loki/compactor
#  compaction_interval: 10m
#  retention_enabled: true
#  retention_delete_delay: 2h
#  retention_delete_worker_count: 150
#
#ingester:
#  lifecycler:
#    address: 127.0.0.1
#    ring:
#      kvstore:
#        store: inmemory
#      replication_factor: 1
#  chunk_idle_period: 5m
#  chunk_retain_period: 30s
#
#limits_config:
#  allow_structured_metadata: true
#  max_streams_per_user: 10000
#
#schema_config:
#  configs:
#    - from: "2020-05-15"
#      index:
#        period: 24h
#        prefix: index_
#      object_store: filesystem
#      schema: v13
#      store: tsdb
#
#server:
#  http_listen_port: 3100
#
#storage_config:
#  tsdb_shipper:
#    active_index_directory: /data/tsdb-index
#    cache_location: /data/tsdb-cache
#  filesystem:
#    directory: /loki/chunks

auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

ingester:
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /loki/compactor

limits_config:
  allow_structured_metadata: true
  max_streams_per_user: 10000
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32

storage_config:
  filesystem:
    directory: /loki/chunks
